// Generated by Lasy AI - https://lasy.ai
import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "InovaTools.AI - Plataforma Definitiva de Criação com IA",
  description: "Edite imagens, crie vídeos virais, gere textos persuasivos e muito mais. Mais de 50 ferramentas de IA em um só lugar.",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "InovaTools.AI",
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    type: "website",
    siteName: "InovaTools.AI",
    title: "InovaTools.AI - Plataforma Definitiva de Criação com IA",
    description: "Edite imagens, crie vídeos virais, gere textos persuasivos e muito mais. Mais de 50 ferramentas de IA em um só lugar.",
  },
  twitter: {
    card: "summary_large_image",
    title: "InovaTools.AI - Plataforma Definitiva de Criação com IA",
    description: "Edite imagens, crie vídeos virais, gere textos persuasivos e muito mais. Mais de 50 ferramentas de IA em um só lugar.",
  },
};

export const viewport: Viewport = {
  themeColor: "#9333ea",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="apple-touch-icon" href="/icon-192.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="InovaTools.AI" />
        <meta name="mobile-web-app-capable" content="yes" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
